version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 851725395125.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=851725395125.dkr.ecr.us-east-1.amazonaws.com/ntm-container
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag my-react-app:latest 637423502407.dkr.ecr.us-east-1.amazonaws.com/myecr:latest
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
  commands:
    - echo Build completed
    - echo pushing to repo
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file...
    # Give your container name
    - DOCKER_CONTAINER_NAME=ntm-app-container
    - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - echo $DOCKER_CONTAINER_NAME
    - echo printing imagedefinitions.json
    - cat imagedefinitions.json
artifacts:
  files: 
   - 'imagedefinitions.json'
   - 'appspec.yml'
   - 'taskdef.json'
